### PR TITLE
Refactor header menu to remove repetitive patterns. 

### PR DESCRIPTION
**Pull request by gschnall**
Also removes the submenu toggle from app mode when not in a mobile view;  because the back arrow and title "Recent Maps" serve no purpose here.
Screen Shot 2019-03-21 at 3 50 03 PM

### CODE REVIEW

**Comment by paulcpederson** [comment]
Wow this is way better, nice work @gschnall 💯

**Comment by gschnall** [comment]
@maccesar21 This should be good now. I forgot to follow my own advice on my PR comment and convert structuredMenu to a boolean lol.

**Comment by maccesar21** [comment]
Looks like it's back to normal @gschnall good job..

**Comment by gschnall** [comment]
@maccesar21 @dlewis-esri thank you for testing this 🍾 . Overall, the columns are looking pretty solid. I think we'll run into some minor issues in other languages when switching to mobile views. We can address this, if necessary, at a later time.

Screen Shot 2019-03-22 at 4 31 32 PM

@maccesar21 would you like to take a shot at putting some info on columns in the docs? More apps might want to use them if they see them there.

https://esri.github.io/global-nav/

**Pull request merged**
