### PR TITLE
Trap focus within account control

### PR DESCRIPTION
**Pull request by MikeTschudi**
[Accessibility: account dropdown doesn't capture focus #306](https://github.com/Esri/global-nav/issues/306)

### CODE REVIEW

**Comment by paulcpederson** [comment]
Thanks @MikeTschudi !

**Comment by MikeTschudi** [comment]
@dlewis-irse, done. Should I remove the tabs in a subsequent PR or are they generally accepted in this rep?

**Comment by dlewis-irse** [comment]
look at https://github.com/Esri/global-nav/pull/307/files/fe364306f6e9e87aafecbcc3f316300102202e76..5a16013afc0c08e25650232517fd06a3079ec219

it should only show the changes that were made.

you may need to abort your branch and cut a new one and configure your IDE to not change the spacing.

I just checked my VSCode and it's set to 
Indent Using Spaces - and Tab Size: 4

I just cut a test branch check the diff here
https://github.com/Esri/global-nav/compare/test?expand=1

see how it only shows the one line I added?

Appreciate the help - just want to make sure we don't throw out file change history or change the line settings for individual files and then future changes will put it back

**Comment by dlewis-irse** [comment]
Scratch that I just checked and it looks good

**Comment by paulcpederson** [comment]
For future reference if you append `?w=1` to any commit or review url in github it will ignore whitespace changes. Like: [https://github.com/Esri/global-nav/pull/307/commits/fe364306f6e9e87aafecbcc3f316300102202e76?w=1](https://github.com/Esri/global-nav/pull/307/commits/fe364306f6e9e87aafecbcc3f316300102202e76?w=1)

**Comment by MikeTschudi** [comment]
Nice tip--thanks, Paul!

**Pull request merged**
