### PR TITLE
Utilize arcgis-app-switcher component

### PR DESCRIPTION
**Pull request by rpanichakit9541**
dependent on https://devtopia.esri.com/WebGIS/arcgis-app-components/pull/2375

I have not found a way to make the global nav pull in arcgis-app-components, so currently the app that wants to use this feature will have to make sure to already have `calcite-components` and `arcgis-app-components`

### CODE REVIEW

**Comment by rpanichakit9541** [comment]
Those are great points.

Do you think it's okay to install this since I didn't remove/change any of the existing functionality only added the additional option?  So places like the Home app that already has all the required dependencies can start utilizing/testing the new component?

**Comment by paulcpederson** [comment]
Yeah, as long as the original way works, I think it's probably OK. Perhaps just add a note to the documentation [after this](https://github.com/Esri/global-nav/blob/master/src/index.html#L425-L500) that quickly outlines those dependencies for folks?

**Comment by rpanichakit9541** [comment]
@paulcpederson - I've added the documentation to index.html.  Let me know if it looks okay to you. Thank you.

**Review by paulcpederson — APPROVED** [review]

**Comment by paulcpederson** [comment]
Nice, Looks good to me, adding @dlewis-irse to see if this makes sense from his perspective

**Comment by dlewis-irse** [comment]
As an FYI - were no longer using this repo for the Global Nav on Esri.com.  That being said the example you gave me in email yesterday should work.  I just haven't had a chance to test it yet

**Pull request merged**
