### PR TITLE
Removes focus ring on buttons in top nav

### PR DESCRIPTION
**Pull request by dlewis-irse**

### CODE REVIEW

**Comment by paulcpederson** [comment]
This is generally a bad idea for accessibility, right?

**Comment by dlewis-irse** [comment]
oh I was just following how our live nav works on esri.com currently - I didn't want to introduce the focus ring on the top links

**Comment by paulcpederson** [comment]
the top links have a focus ring on esri.com... this would remove it?

**Comment by dlewis-irse** [comment]
not currently but when I was testing with the latest code as we are prepping to do a deployment I was getting them - If were supposed to have them for accessibility though I'm fine leaving them till someone complains

**Pull request closed without merging**
